// store
export const RESET_SELECTED_AGREEMENT = 'RESET__SELECTED_AGREEMENT';
export const ASSIGN_SELECTED_AGREEMENT = 'ASSIGN_SELECTED_AGREEMENT';
export const ASSIGN_AGREEMENTS = 'ASSIGN_AGREEMENTS';
export const DELETE_AGREEMENT = 'DELETE_AGREEMENT';
